'use strict';

const Homey = require('homey');
// Uncomment while debugging a new Zigbee device to dump every frame the app
// sends/receives to the app logs. Very noisy — leave off in normal use.
// const { Cluster, debug } = require('zigbee-clusters');

const errlog = require('./lib/errlog');

class ZigbidouilleApp extends Homey.App {
  async onInit() {
    // debug(true); // pair with the line above to trace raw Zigbee traffic
    // Restores the log persisted by the previous run, so evidence from a
    // pairing that crashed the app is still readable in the settings page.
    errlog.init(this.homey);
    errlog.info('app', 'Zigbidouille started');
    this.log('Zigbidouille started');

    this.registerVacuumFlows();
    this.registerDevialetFlows();
    this.registerRemoteFlows();
    this.registerImouFlows();
  }

  // The dimmer fires one trigger for every button event; this listener is what
  // narrows a flow down to the button and the kind of press it asked for.
  // Without it the card would run on every button of the remote.
  registerRemoteFlows() {
    this.homey.flow
      .getDeviceTriggerCard('hue_dimmer_pressed')
      .registerRunListener((args, state) => args.button === state.button && args.action === state.action);
  }

  // "Set the source" is the card that makes the speakers actually useful in a
  // flow — switching to the right speaker's jack, or back to Spotify.
  registerDevialetFlows() {
    this.homey.flow
      .getActionCard('devialet_set_source')
      .registerRunListener(({ device, source }) => device.selectSource(source));

    this.homey.flow
      .getActionCard('devialet_volume_step')
      .registerRunListener(({ device, delta }) => device.stepVolume(Number(delta)));
  }

  // Flow cards for the miIO vacuum (drivers/x20plus). Zigbee drivers here need
  // none: their capabilities give Homey the standard cards for free. The vacuum
  // exposes actions with no matching capability, so they are wired by hand.
  registerVacuumFlows() {
    // Two explicit resume actions, deliberately. From a paused dock-return,
    // sending "resume cleaning" starts a brand-new clean of the whole home, so
    // the flow author picks — the app never guesses.
    const actions = {
      start_cleaning: (device) => device.startCleaning(),
      resume_cleaning: (device) => device.resumeCleaning(),
      resume_returning: (device) => device.resumeReturning(),
      pause: (device) => device.pause(),
    };

    for (const [card, run] of Object.entries(actions)) {
      this.homey.flow.getActionCard(card).registerRunListener(({ device }) => run(device));
    }

    // Conditions read the capability, never an instance variable: it holds the
    // displayed state, is refreshed every poll, and matches the ids the cards
    // offer. A condition once compared a raw status code to a state id and
    // silently never matched.
    this.homey.flow
      .getConditionCard('is_paused_from')
      .registerRunListener(({ device, reason }) => device.getCapabilityValue('vacuum_status') === `paused_${reason}`);

    this.homey.flow
      .getConditionCard('status_is')
      .registerRunListener(({ device, status }) => device.getCapabilityValue('vacuum_status') === status);
  }

  // Imou cameras (drivers/imou-ranger2c, drivers/imou-cellpt). On/off pairs
  // rather than a single "set" card with a dropdown: it matches how the rest
  // of this app's action cards read in a flow, and there is no device setting
  // to keep off Homey's autogenerated flow — privacy_mode/motion_detection are
  // custom capabilities, so nothing here is free.
  registerImouFlows() {
    const actions = {
      imou_privacy_on: (device) => device.setSwitchByCapability('privacy_mode', true),
      imou_privacy_off: (device) => device.setSwitchByCapability('privacy_mode', false),
      imou_motion_on: (device) => device.setSwitchByCapability('motion_detection', true),
      imou_motion_off: (device) => device.setSwitchByCapability('motion_detection', false),
    };
    for (const [card, run] of Object.entries(actions)) {
      this.homey.flow.getActionCard(card).registerRunListener(({ device }) => run(device));
    }

    this.homey.flow
      .getConditionCard('imou_privacy_is')
      .registerRunListener(({ device }) => Boolean(device.getCapabilityValue('privacy_mode')));

    this.homey.flow
      .getConditionCard('imou_motion_is')
      .registerRunListener(({ device }) => Boolean(device.getCapabilityValue('motion_detection')));

    // Reads the inverse: the capability is alarm_offline (true == a problem,
    // which is what gives it alarm styling on the tile), the card asks the
    // friendlier "is it online".
    this.homey.flow
      .getConditionCard('imou_is_online')
      .registerRunListener(({ device }) => !device.getCapabilityValue('alarm_offline'));
  }
}

module.exports = ZigbidouilleApp;
